export const ACTION_TYPES = {
    CREATE: 'CREATE',
    UPDATE: 'UDATE',
    DELETE: 'DELETE',
    FETCH_ALL: 'FETCH_ALL',
    SELECT_BOOK:  'SELECT_BOOK',
    CANCEL_SELECTED_BOOK: 'CANCEL_SELECTED_BOOK',
    //OPEN_FORM: 'OPEN_FORM',
   // CLOSE_FORM: 'CLOSE_FORM',
    SET_LOADING: 'SET_LOADING',
    SET_ERROR_MESSAGE: 'SET_ERROR_MESSAGE',
    CLEAR_ERROR_MESSAGE: 'CLEAR_ERROR_MESSAGE',
    CANCEL_SUBMITTING: 'CANCEL_SUBMITTING',
    SET_PAGING_PARAMS: 'SET_PAGING_PARAMS'
}